import Head from 'next/head'
import styled from 'styled-components'
import { Container, Main } from '../components/sharedstyles'
import useSWR from 'swr'

// function to fetch a particular url and return the data as json
const fetcher = url => fetch(url).then(r=> r.json())

export default function Authors() {
  const { data, error } = useSWR(`api/authors`, fetcher)

  // if api encounters an error, this will render
  if (error){
    return <Main>Error!</Main>
  }

  // while data is loading
  if (!data){
    return <Main>Loading ... </Main>
  }

  // then this is the final/ideal rendering if data comes back as expected
  return (
    <SingleBook>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <h1>ALL AUTHORS:</h1>
        <AuthorList>
          {data.map((author, index) => (
            <Author key={index}>{author}</Author>
          ))}
        </AuthorList>
      </Main>
    </SingleBook>
  )
}

const SingleBook = styled.div`
  background-color: #9ccaff;
`

const AuthorList = styled.div`
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 1rem;
`

const Author = styled.div`
  background-color: #fff;
  text-align: center;
  padding: 1rem;
  border-radius: 0.5rem;
  border-radius: 5px;
`
