import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import Cards from '../components/cards'
import styled from 'styled-components'
import useSWR from 'swr';
import BookList from "../components/BookList"


//function to fetch a particular url and return the data as json
const fetcher = url => fetch(url).then(r=> r.json());

export default function Home() {
  //first parameter is the path of the api endpoint (what will be fetched)
  //second param is the fetcher function that executes to get the data
  const {data, error} = useSWR('api/books', fetcher);


  //if api encounters an error, this will render. 
  if (error){
    return <Main>Error!</Main>
  }

  //while data is loading
  if (!data){
    return <Main>Loading ... </Main>
  }

  //then this is the final/ideal rendering. if data comes back as expected
  return (
    <BookShelf>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 style= {{textAlign:'center'}}>NOELA'S MINI LIBRARY</h1>
        <BookList books={data}></BookList>
    </BookShelf>
  )
}

const BookShelf = styled.div`
  background-color: #9ccaff;
  padding: 20px;
  gap: 30px;
`
